services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    deploy:
      placement:
        constraints: [node.role == manager] # node.hostname == laptop1_hostname
    networks:
      - app-network

  backend:
    build:
      context: ./flask-engine
    # command: python scripts/create_admin.py
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=drs_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/drs_db
    deploy:
      placement:
        constraints: [node.role == worker]
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads
    networks:
      - app-network

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drs_db
    deploy:
      placement:
        constraints: [node.role == worker]
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
