"""empty message

Revision ID: 19654be436a3
Revises: 
Create Date: 2024-11-28 16:48:04.162585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19654be436a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=220), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
