"""empty message

Revision ID: 743cbf351d78
Revises: 7347e4d39c19
Create Date: 2024-11-29 22:58:33.255118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743cbf351d78'
down_revision = '7347e4d39c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('acceepted')

    # ### end Alembic commands ###
