"""empty message

Revision ID: 892925e5ac53
Revises: 983b1522f2a7
Create Date: 2024-11-26 17:09:53.926778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '892925e5ac53'
down_revision = '983b1522f2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
