"""empty message

Revision ID: 983b1522f2a7
Revises: 
Create Date: 2024-11-26 16:55:47.431841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983b1522f2a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=220), nullable=True),
    sa.Column('image_path', sa.String(length=250), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
